- accel-pppd/accel-ppp.conf.5
- accel-pppd/ctrl/pppoe/cli.c
- accel-pppd/ctrl/pppoe/pppoe.c
- accel-pppd/ctrl/pppoe/pppoe.h
It is possible to specify multiple service names now (as in most pppoe daemons), old options are backward compatible.
Also new accel-ppp verifying if service-name specified, it should strictly match on PADI and PADR packets, while old version doesn't do that. It is usual ISP scenario, where some clients has service-name specified, and some are "default". Without this patch default without service-name wont be able to connect.
> Multiple service-name, compatibility with old accel-ppp with service name specified

- crypto/tomcrypt_cfg.h
- crypto/tomcrypt_macros.h
tomcrypt_macros.h was missed in 9739251101bffde2c62ba08c1869eb170d952d5b
amd64 machines need unsigned long long type for succesful build
> crypto: internal: add missed header and fix x64 build

- accel-pppd/ipv6/dhcpv6.h
- accel-pppd/ipv6/dhcpv6_packet.c
Vendor-Class, Vendor-Specific and Interface-ID options are binary, opaque and may have variable length, so print them just in hex.
> ipv6: dhcpv6: logging fixes

- accel-pppd/extra/pppd_compat.c
- accel-pppd/ifcfg.c
- accel-pppd/ipdb.h
- accel-pppd/ipv6/dhcpv6.c
- accel-pppd/ipv6/nd.c
Mainly this makes possible to use small prefixes for delegation.
RA messages are still required for deplying default route, RDNSS, etc with non-/64 prefixes.
AdvOnLinkFlag allows tune prefix route behavior, if required.
> ipv6: nd: add non-/64 prefixes & AdvOnLinkFlag option support

- accel-pppd/ctrl/l2tp/packet.c
After session is freed on our end, kernel doesn't bother with possible
incoming data packets and just passes them to userspace, in turn
they are mistreated as short control packets with corresponding errors.
Since there's no special data packet handling, just ignore them.
> l2tp: skip obsolete session data packets from logging

- accel-pppd/ctrl/l2tp/l2tp.c
- accel-pppd/ctrl/pptp/pptp.c
With echo-falure properly set, pptp channel might be disconnected on any fail number (i.e on first fail, never), due failed echo counter contains random value, not actual fail count.
With incoming pptp echo request/l2tp hello there's no need to ask peer for replies in configured echo-interval, assuming the channel is working.  So just postpone next request.
It helps against false-positive echo failures with heavily loaded channels and/or peers.
> pptp/l2tp: echo failure improvements

- accel-pppd/accel-ppp.conf
- accel-pppd/accel-ppp.conf.5
- accel-pppd/ctrl/l2tp/l2tp.c
- accel-pppd/ctrl/pppoe/pppoe.c
- accel-pppd/ctrl/pptp/pptp.c
- accel-pppd/ifcfg.c
Reuse exsisting radius functionality and allow set iterface name template for pppoe/pptp/l2tp, '%d' specification will be replaced automagically to the next available index by kernel.
PPP interface rename allows to easy differ client's interfaces from the other ppp ones, for example, with just netfilter interface rules.
Example:
[pptp]
ifname=pptp%d will produce pptp0, pptp1, ...
> ppp: implement per-ctrl ppp interface rename support

- accel-pppd/extra/chap-secrets.c
Chap-secrets' ipdb uses 4th field as static peer ipv4 address. With no radius and multiple same username sessions, it's impossible to use non-default pool for such sessions.
Abuse chap-secret's 4th field as pool=name to specify session's pool name.
With ippool module loaded after chap-secrets (default order), it will be used for allocation from the specified poll name.
Compatibility considerations:
* pppd will skip 'pool=*' with warn 'unknown host in auth. address list' same as 5th field - shaper, because starting from 4th field pppd parse list of value. so, no new effects here.
* previous versions of accel-ppp will parse 'pool=*' as invalid 255.255.255.255 address.
* with no 'pool=*' in chap-secrets or with no chap-secrets loaded, no behavior change.
* with no ippool loaded, session will …
> chap-secrets: add pool name support

- accel-pppd/ifcfg.c
> ppp: fix interface rename if kernel returns not zero, but picked index

- accel-pppd/triton/triton.c
since alloca() result is used indirectly, gcc 4.7.2 thinks
the whole call can be dropped on any optimization level.
fixes issue #29
> triton: fix crash due gcc mis-optimization of alloca()

- accel-pppd/extra/pppd_compat.c
- accel-pppd/ifcfg.c
- accel-pppd/ipdb.c
- accel-pppd/ipv6/dhcpv6.c
- accel-pppd/ipv6/dhcpv6_packet.c
- accel-pppd/ipv6/nd.c
- accel-pppd/libnetlink/iputils.c
Prefix range from /65 to /127 handling is consolidated to be consistent in all places.
Conflict between equal local and peer addrs is solved by inversing local interface id.
The last one patch changes PD routes' nexthop from all the peer's addresses to one peer's linklocal address.
> Ipv6 pool fixes

- accel-pppd/ppp/lcp_opt_mru.c
- accel-pppd/ppp/ppp.c
fixed interface mtu setup was skipped in unit-preallocate mode.
fixed channel/unit mru setup if not negotiated in unit-cache mode.
also, if not negotiated, mru must not be lower than default 1500 per RFC and peer expectations.
> ppp: fix mtu/mru negotiation in unit-preallocate/unit-cache modes

- accel-cmd/accel-cmd.1
- accel-cmd/accel_cmd.c
Useful for accel-cmd oneliners when cli password is set.
Existing behavior is not affected, incl. echo "...multiline..." | accel-cmd with password on 1st line
> accel-cmd: add -P/--password support

- accel-pppd/ctrl/ipoe/arp.c
- accel-pppd/ctrl/pppoe/pppoe.c
Fixes sending of the arp replies with fresh kernels
3.18.132, 4.4.170, 4.9.149, 4.14.92, 4.19.14, 4.20
> Fix work on fresh kernels

- accel-pppd/ctrl/l2tp/l2tp.c
@dyangol investigated that this were the field MPD5 tunnels required to make accel-ppp work for [bsdrp](https://bsdrp.net/) routers
I don't know if there is a better way to handle that
> Added extra AVP to SCCCN as known to allow MPD5 tunnels

- cmake/cpack.cmake
On Debian 10 (Buster) it is impossible to install Accel-PPP due to required different OpenSSL version in deb file, while compilation passing smoothly and binaries are operational.
Added CPack Debian10 option
> Added support for Debian10 DEB pack generation

- accel-pppd/radius/acct.c
Accounting stop is sent with the same id as the last Interium-update id. 
In some cases, when interium-update and stop packets are sent almost simultaneously 
(e.g. when acct-interim-interval and lease-time are equal),
RADIUS could generate error:
_Discarding conflicting packet from client due to recent request for second packet._
> [Fix] - Increment Accounting-Request id for Acct-Status-Type Stop

- accel-pppd/accel-ppp.conf
- accel-pppd/accel-ppp.conf.5
- accel-pppd/ctrl/sstp/sstp.c
openssl 1.1.1 has no SSLv2/SSLv3 support and defaults to TLSv1.2 as minimum, what breaks old SSTP client connections via TLSv1.
now it's possible to set ssl-protocol to tls1,tls1.1,tls1.2,tls1.3 if needed.
in case of some protocols/DH/ECDH not supported by openssl library, corresponding warnings will be logged.
> sstp: implement ssl-protocol option and add unsupported features logging

- accel-pppd/accel-ppp.conf.5
- accel-pppd/ctrl/ipoe/ipoe.c
- accel-pppd/ppp/ipcp_opt_ipaddr.c
- accel-pppd/ppp/ipv6cp_opt_intfid.c
let check-ip setting from [ppp]/[ipoe] sections has prio over [common]
for compatibility with older configs.
> ppp/ipoe: cleanup cleck-ip support

- accel-pppd/radius/backup.c
- accel-pppd/radius/dm_coa.c
- accel-pppd/radius/radius.c
- accel-pppd/radius/radius_p.h
- accel-pppd/radius/req.c
once radius server has returned User-Name attribute in Access-Accept
packet, it'll be used for any subsequent Accounting-Request packets
instead of internal username per RFC2865 5.1
other way of just replacing session username is possible, but not
desired at the moment due potential issues with single-session modes
in case of different ppp logins / ipoe macs and same contract number
returned by radius for that accounts.
also, add logging & parsing of invalid dm/coa packet for easier debug
> radius: add support for Access-Accept username

- accel-pppd/accel-ppp.conf
- accel-pppd/accel-ppp.conf.5
- accel-pppd/session.c
If multisession behavior is managed by accel-ppp and Radius server
ignores the case of the User-Name attribute, it might be required to
ignore the case in accel-ppp to prevent multiple session with
different letter cases.
> Added single-session-ignore-case option

- accel-pppd/ctrl/ipoe/dhcpv4.c
packet flattening allows to calc csums in single pass.
at the other hand, keeping vectorized raw packet would require partial csum calculation, not sure should we bother with it for small dhcp packets < 576.
> ipoe: dhcp: implement udp csum and padding per rfc1542

- accel-pppd/ctrl/ipoe/dhcpv4.c
there're some onu in the wild, which insert opt82 in relayed requests and drop any unmatching replies (w/o same opt82).
to fix that, need to improve dhcp compliance for following rc3046 parts:
>2.1 Agent Operation
>  The Relay Agent Information option echoed by a server MUST be removed
>   by either the relay agent or the trusted downstream network element
>   which added it when forwarding a server-to-client response back to
>   the client.
>
>2.2 Server Operation
>  DHCP servers claiming to support the Relay Agent Information option
>   SHALL echo the entire contents of the Relay Agent Information option
>   in all replies.  Servers SHOULD copy the Relay Agent Information
>   option as the last DHCP option in the response.
> ipoe: dhcpv4: echo back opt82 if sent by client/relay per rfc3046

- accel-pppd/accel-ppp.conf
- accel-pppd/accel-ppp.conf.5
- accel-pppd/ctrl/ipoe/ipoe.c
- accel-pppd/ctrl/l2tp/l2tp.c
- accel-pppd/ctrl/pppoe/pppoe.c
- accel-pppd/ctrl/pptp/pptp.c
- accel-pppd/ctrl/sstp/sstp.c
- accel-pppd/include/ap_session.h
- accel-pppd/session.c
Usually there's no need to have per-proto limitation, since the need of max starting limitation affects the whole server, not particular protocol only.
So, instead of different [ipoe|pptp], non-working [pppoe] and absent [l2tp|sstp] max-starting options, let's have one general [common]max-starting for all of them.
Under new session storm (kind of DDoS) no logging is helpful. Since we have no rate-limited logging, let's remove it complitely alike max-session and connlimit do.
Also, max-sessions was not applied to sstp, fix that.
> Add global [common]max-starting option

- accel-cmd/accel_cmd.c
With GCC v8.x on Raspbian Buster the following warning is shown
at compile time:
...
[ 99%] Building C object accel-cmd/CMakeFiles/accel-cmd.dir/accel_cmd.c.o
/home/pi/accel-ppp/accel-cmd/accel_cmd.c: In function ‘main’:
/home/pi/accel-ppp/accel-cmd/accel_cmd.c:652:29: warning: comparison is always true due to limited range of data type [-Wtype-limits]
long_opts, &oindx)) != -1) {
^~
[100%] Linking C executable accel-cmd
[100%] Built target accel-cmd
This leads to the accel-cmd always just showing the usage
instructions rather than executing any commands.
This is because ochar is declared as a char rather than an int
so is considered to be unsigned by default. The man page says
the return value should be an int.
https://linux.die.net/man/3/getopt_long
> Fix accel-cmd compile problem on Raspbian Buster

- accel-pppd/ifcfg.c
- accel-pppd/include/ap_net.h
- accel-pppd/net.c
- accel-pppd/ppp/ppp.c
- accel-pppd/session.c
When a network interface is moved to another network namespace, it might be reindexed if its current index conflicts with one already used in the new namespace. This patchset refreshes our record of the index any time we move the interface around.
> Refresh interface index when moving to another netns
